### PR TITLE
feat: update secondary button colors, according to latest design

### PR DESCRIPTION
**Pull request by pducolin**
Less funny, still useful PR to update secondary button design 
Before:
before
After:
after

### CODE REVIEW

**Comment by oclero** [comment]
By the way, there is no generated docs?

**Comment by a-coruble** [comment]
There should be a generated change for the tests I think no ? By the way, do you have screen captures of before / after ?

**Comment by pducolin** [comment]
That's weird indeed

**Comment by pducolin** [comment]
> There should be a generated change for the tests I think no ? By the way, do you have screen captures of before / after ?

No changes in snapshots. A snapshot doesn't include colors, for the secondary button the snapshot is ```

<Component
  nature="secondary"
>
  <button
    className="button secondary medium light"
  />
</Component>
```

Added gif of before / after

**Pull request merged**
