### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by goldins**

### CODE REVIEW

**Review by therealglazou — APPROVED** [review]
a=me

**Comment by ni0ki** [comment]
Summary of licenses used in the project  (`npx license-checker --summary`) : 

├─ MIT: 2190
├─ ISC: 212
├─ BSD-2-Clause: 50
├─ Apache-2.0: 49
├─ BSD-3-Clause: 46
├─ MIT*: 14
├─ CC0-1.0: 6
├─ (MIT OR CC0-1.0): 5
├─ BSD*: 4
├─ Artistic-2.0: 4
├─ CC-BY-4.0: 3
├─ (WTFPL OR MIT): 3
├─ (MIT OR Apache-2.0): 2
├─ WTFPL: 2
├─ (BSD-2-Clause OR MIT OR Apache-2.0): 2
├─ Apache License, Version 2.0: 2
├─ CC-BY-3.0: 2
├─ Unlicense: 2
├─ BSD: 1
├─ AFLv2.1,BSD: 1
├─ Public Domain: 1
├─ (BSD-3-Clause OR GPL-2.0): 1
├─ (MIT AND Zlib): 1
├─ Apache 2.0: 1
├─ (MIT AND BSD-3-Clause): 1
├─ (BSD-2-Clause OR MIT): 1
└─ 0BSD: 1

Seems we **might** have a GPL 2.0, I'm trying to check

**Review by ni0ki — APPROVED** [review]

**Review by ni0ki — DISMISSED** [review]

**Review by ni0ki — APPROVED** [review]

**Review by perrywortman — DISMISSED** [review]
Approved

**Comment by goldins** [comment]
had to update the PR with signed commits, needs re-approval.

**Review by perrywortman — APPROVED** [review]

**Review by ni0ki — APPROVED** [review]

**Pull request merged**
